name: Build and Deploy Dockerfile
run-name: ${{ github.actor }} is building Docker Images
on: [ push ]
jobs:
  build-images:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: chmod +x ./build.sh
      - name: Create Package
        run: ./build.sh
